### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by suliman3** [lutianming/cartoonizer#1]
![Screenshot (76)](https://user-images.githubusercontent.com/57145770/67782617-44b62600-fa26-11e9-8160-1e4ab56b28ce.png)
cartoonizer.py didn't work
the error:
usage: cartoonizer.py [-h] input output
cartoonizer.py: error: the following arguments are required: input, output

**Comment by codingjustahobby** [comment]
I think it is because you are using pycharm and your program requires arguments it is not running , use the command line to see

**Comment by ejlai** [comment]
You shall try the test.py where you can provide input and output.
